### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by ForeverButthurt** [wyozi/wmc#45]
[ERROR] addons/media_ttt/lua/cl_wmc_tttx.lua:236: attempt to index field 'TTT_PauseData' (a nil value)
  1. fn - addons/media_ttt/lua/cl_wmc_tttx.lua:236
   2. CallHook - addons/ulib/lua/ulib/shared/hook.lua:183
    3. pre_play - addons/media_base/lua/cl_wmc_player2.lua:32
     4. play_url - addons/media_base/lua/cl_wmc_media.lua:73
      5. func - addons/media_base/lua/cl_wmc_player2.lua:100
       6. unknown - lua/includes/modules/net.lua:32

**Comment by wyozi** [comment]
This is not the repository for WMC extensions.

However, your problem seems to be that you're using an outdated version of WMC: TTT.
