### ISSUE TITLE
How Do I Use This ? 

### ISSUE THREAD

**Issue by BasonTaylor** [wyozi/wmc#46]
The Read ME does not exsplain how to set it all up

**Comment by wyozi** [comment]
It's an addon. You unzip it all to a folder in the addons folder.

Use F9 to open the GUI.

**Comment by BasonTaylor** [comment]
well how do i spawn the theater thing?

**Comment by BasonTaylor** [comment]
for youtubz

**Comment by wyozi** [comment]
There is nothing to spawn in this addon. You probably mean the darkrp extension to WMC which is not available on github or anywhere really.
