### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by k2nod** [wyozi/wmc#48]
[ERROR] addons/wmc-master/lua/cl_wmc_gui.lua:111: attempt to call field 'PlayUrl' (a nil value)
  1. DoClick - addons/wmc-master/lua/cl_wmc_gui.lua:111
   2. OnMouseReleased - lua/vgui/dlabel.lua:218
    3. unknown - lua/vgui/dmenuoption.lua:116

**Comment by wyozi** [comment]
Read installation instructions.
